baseURL: "https://www.reneesworkspace.com/"
languageCode: en-us
title: Renee's Workspace
theme: PaperMod

params:
  homeInfoParams:
    Title: "Hi there, welcome to my public workspace."
    Content: This is a space for me to explore my interests. 
    You'll find writing, musings and workflows spanning digital workspaces, systems, organization, philosophy, creativity and life in general.
    Explore  

  cover:
    linkFullImages: false

  ShowBreadCrumbs: true 

  ShowReadingTime: false

  ShowShareButtons: false

  ShowToc: true

  ShowPostNavLinks: false

menu:
  main:
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 10
    - identifier: archive
      name: Archive
      url: /archive/
      weight: 20
    - identifier: library
      name: Library
      url: /library/
      weight: 30
    - identifier: timeline
      name: Timeline
      url: /timeline/
      weight: 40
    - identifier: explore
      name: Explore
      url: /explore/
      weight: 50

params:
  # for enhanced SEO
  env: production
